apiVersion: v2
name: etcd-defrag
description: etcd-defrag is an easy to use and smart etcd defragmentation tool.
type: application
version: 1.2.3
# repo: ahrtr/etcd-defrag
appVersion: v0.36.0
home: https://github.com/giantswarm/etcd-defrag-app
icon: https://s.giantswarm.io/app-icons/giantswarm/1/dark.svg
annotations:
  application.giantswarm.io/team: tenet
